### ISSUE TITLE
Test Case for Custom User Model

### ISSUE THREAD

**Issue by aniketmaithani** [jonathanchu/django-custom-user-example#5]
Since this app is sort of generic (for newbies who just needs plug and play integration) @jonathanchu why not add test cases for the custom user model. Your take?

**Comment by jonathanchu** [comment]
Hey @aniketmaithani - good idea!  This repo was really meant to be an example of how to implement a custom user model when Django v1.5 came out, but I think this is a good idea and good practice nonetheless to include some tests.  

The tests themselves would need to be somewhat generic as we would want to test the implementation of this custom user model and not any of its specific attributes, as that would vary by use-case.  The tests should be a starting point for the user to build off of in the future.

I'll definitely take a stab at this when I get some free time this week, but please do feel free to submit any PRs yourself and I'll be more than happy to merge :)

**Comment by aniketmaithani** [comment]
@jonathanchu I am on it. I am sending the PR right away.

**Comment by aniketmaithani** [comment]
Hey @jonathanchu you can close this issue after referencing the request merged. :)

**Comment by jonathanchu** [comment]
Cheers, thanks again! :beers: :smiley_cat:
