### ISSUE TITLE
cannot create superuser

### ISSUE THREAD

**Issue by OnlyBelter** [jonathanchu/django-custom-user-example#9]
When I run `python manage.py createsuperuser`, I got the following error:

```
ERRORS:
myapp.CustomUser.is_superuser: (models.E006) The field 'is_superuser' clash
es with the field 'is_superuser' from model 'myapp.customuser'.
```

**Comment by OnlyBelter** [comment]
I have fixed it, please see here, https://stackoverflow.com/questions/46093946/django-1-10-custom-user-is-superuser-clashes-with-the-field-is-superuser-fro

**Comment by jonathanchu** [comment]
Ah cheers, thanks @OnlyBelter!  I should update the repo to reflect this - it is most definitely a few Django versions behind.

Thanks again!
